# Generated by Django 6.0.2 on 2026-03-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velvetra2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designproject',
            name='designer',
        ),
        migrations.AddField(
            model_name='designer',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designproject',
            name='designer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='designproject',
            name='final_approved',
            field=models.BooleanField(default=False),
        ),
    ]
